/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BnsGetNamePriceResponse Fetch price for name.
type BnsGetNamePriceResponse struct {
	Units string `json:"units"`
	Amount string `json:"amount"`
}

// NewBnsGetNamePriceResponse instantiates a new BnsGetNamePriceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsGetNamePriceResponse(units string, amount string) *BnsGetNamePriceResponse {
	this := BnsGetNamePriceResponse{}
	this.Units = units
	this.Amount = amount
	return &this
}

// NewBnsGetNamePriceResponseWithDefaults instantiates a new BnsGetNamePriceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsGetNamePriceResponseWithDefaults() *BnsGetNamePriceResponse {
	this := BnsGetNamePriceResponse{}
	return &this
}

// GetUnits returns the Units field value
func (o *BnsGetNamePriceResponse) GetUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Units
}

// GetUnitsOk returns a tuple with the Units field value
// and a boolean to check if the value has been set.
func (o *BnsGetNamePriceResponse) GetUnitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Units, true
}

// SetUnits sets field value
func (o *BnsGetNamePriceResponse) SetUnits(v string) {
	o.Units = v
}

// GetAmount returns the Amount field value
func (o *BnsGetNamePriceResponse) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *BnsGetNamePriceResponse) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *BnsGetNamePriceResponse) SetAmount(v string) {
	o.Amount = v
}

func (o BnsGetNamePriceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["units"] = o.Units
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableBnsGetNamePriceResponse struct {
	value *BnsGetNamePriceResponse
	isSet bool
}

func (v NullableBnsGetNamePriceResponse) Get() *BnsGetNamePriceResponse {
	return v.value
}

func (v *NullableBnsGetNamePriceResponse) Set(val *BnsGetNamePriceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsGetNamePriceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsGetNamePriceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsGetNamePriceResponse(val *BnsGetNamePriceResponse) *NullableBnsGetNamePriceResponse {
	return &NullableBnsGetNamePriceResponse{value: val, isSet: true}
}

func (v NullableBnsGetNamePriceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsGetNamePriceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


