/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CoinbaseTransactionMetadataCoinbasePayload struct for CoinbaseTransactionMetadataCoinbasePayload
type CoinbaseTransactionMetadataCoinbasePayload struct {
	// Hex encoded 32-byte scratch space for block leader's use
	Data string `json:"data"`
}

// NewCoinbaseTransactionMetadataCoinbasePayload instantiates a new CoinbaseTransactionMetadataCoinbasePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoinbaseTransactionMetadataCoinbasePayload(data string) *CoinbaseTransactionMetadataCoinbasePayload {
	this := CoinbaseTransactionMetadataCoinbasePayload{}
	this.Data = data
	return &this
}

// NewCoinbaseTransactionMetadataCoinbasePayloadWithDefaults instantiates a new CoinbaseTransactionMetadataCoinbasePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoinbaseTransactionMetadataCoinbasePayloadWithDefaults() *CoinbaseTransactionMetadataCoinbasePayload {
	this := CoinbaseTransactionMetadataCoinbasePayload{}
	return &this
}

// GetData returns the Data field value
func (o *CoinbaseTransactionMetadataCoinbasePayload) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CoinbaseTransactionMetadataCoinbasePayload) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CoinbaseTransactionMetadataCoinbasePayload) SetData(v string) {
	o.Data = v
}

func (o CoinbaseTransactionMetadataCoinbasePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCoinbaseTransactionMetadataCoinbasePayload struct {
	value *CoinbaseTransactionMetadataCoinbasePayload
	isSet bool
}

func (v NullableCoinbaseTransactionMetadataCoinbasePayload) Get() *CoinbaseTransactionMetadataCoinbasePayload {
	return v.value
}

func (v *NullableCoinbaseTransactionMetadataCoinbasePayload) Set(val *CoinbaseTransactionMetadataCoinbasePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCoinbaseTransactionMetadataCoinbasePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCoinbaseTransactionMetadataCoinbasePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoinbaseTransactionMetadataCoinbasePayload(val *CoinbaseTransactionMetadataCoinbasePayload) *NullableCoinbaseTransactionMetadataCoinbasePayload {
	return &NullableCoinbaseTransactionMetadataCoinbasePayload{value: val, isSet: true}
}

func (v NullableCoinbaseTransactionMetadataCoinbasePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoinbaseTransactionMetadataCoinbasePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


