/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AbstractMempoolTransactionAllOf struct for AbstractMempoolTransactionAllOf
type AbstractMempoolTransactionAllOf struct {
	// Status of the transaction
	TxStatus string `json:"tx_status"`
	// A unix timestamp (in seconds) indicating when the transaction broadcast was received by the node.
	ReceiptTime float32 `json:"receipt_time"`
	// An ISO 8601 (YYYY-MM-DDTHH:mm:ss.sssZ) timestamp indicating when the transaction broadcast was received by the node.
	ReceiptTimeIso string `json:"receipt_time_iso"`
}

// NewAbstractMempoolTransactionAllOf instantiates a new AbstractMempoolTransactionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAbstractMempoolTransactionAllOf(txStatus string, receiptTime float32, receiptTimeIso string) *AbstractMempoolTransactionAllOf {
	this := AbstractMempoolTransactionAllOf{}
	this.TxStatus = txStatus
	this.ReceiptTime = receiptTime
	this.ReceiptTimeIso = receiptTimeIso
	return &this
}

// NewAbstractMempoolTransactionAllOfWithDefaults instantiates a new AbstractMempoolTransactionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAbstractMempoolTransactionAllOfWithDefaults() *AbstractMempoolTransactionAllOf {
	this := AbstractMempoolTransactionAllOf{}
	return &this
}

// GetTxStatus returns the TxStatus field value
func (o *AbstractMempoolTransactionAllOf) GetTxStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxStatus
}

// GetTxStatusOk returns a tuple with the TxStatus field value
// and a boolean to check if the value has been set.
func (o *AbstractMempoolTransactionAllOf) GetTxStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxStatus, true
}

// SetTxStatus sets field value
func (o *AbstractMempoolTransactionAllOf) SetTxStatus(v string) {
	o.TxStatus = v
}

// GetReceiptTime returns the ReceiptTime field value
func (o *AbstractMempoolTransactionAllOf) GetReceiptTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ReceiptTime
}

// GetReceiptTimeOk returns a tuple with the ReceiptTime field value
// and a boolean to check if the value has been set.
func (o *AbstractMempoolTransactionAllOf) GetReceiptTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiptTime, true
}

// SetReceiptTime sets field value
func (o *AbstractMempoolTransactionAllOf) SetReceiptTime(v float32) {
	o.ReceiptTime = v
}

// GetReceiptTimeIso returns the ReceiptTimeIso field value
func (o *AbstractMempoolTransactionAllOf) GetReceiptTimeIso() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceiptTimeIso
}

// GetReceiptTimeIsoOk returns a tuple with the ReceiptTimeIso field value
// and a boolean to check if the value has been set.
func (o *AbstractMempoolTransactionAllOf) GetReceiptTimeIsoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiptTimeIso, true
}

// SetReceiptTimeIso sets field value
func (o *AbstractMempoolTransactionAllOf) SetReceiptTimeIso(v string) {
	o.ReceiptTimeIso = v
}

func (o AbstractMempoolTransactionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tx_status"] = o.TxStatus
	}
	if true {
		toSerialize["receipt_time"] = o.ReceiptTime
	}
	if true {
		toSerialize["receipt_time_iso"] = o.ReceiptTimeIso
	}
	return json.Marshal(toSerialize)
}

type NullableAbstractMempoolTransactionAllOf struct {
	value *AbstractMempoolTransactionAllOf
	isSet bool
}

func (v NullableAbstractMempoolTransactionAllOf) Get() *AbstractMempoolTransactionAllOf {
	return v.value
}

func (v *NullableAbstractMempoolTransactionAllOf) Set(val *AbstractMempoolTransactionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAbstractMempoolTransactionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAbstractMempoolTransactionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAbstractMempoolTransactionAllOf(val *AbstractMempoolTransactionAllOf) *NullableAbstractMempoolTransactionAllOf {
	return &NullableAbstractMempoolTransactionAllOf{value: val, isSet: true}
}

func (v NullableAbstractMempoolTransactionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAbstractMempoolTransactionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


