/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TokenTransferTransaction Describes representation of a Type-0 Stacks 2.0 transaction. https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-005-blocks-and-transactions.md#type-0-transferring-an-asset
type TokenTransferTransaction struct {
	TxType string `json:"tx_type"`
	TokenTransfer TokenTransferTransactionMetadataTokenTransfer `json:"token_transfer"`
}

// NewTokenTransferTransaction instantiates a new TokenTransferTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTransferTransaction(txType string, tokenTransfer TokenTransferTransactionMetadataTokenTransfer) *TokenTransferTransaction {
	this := TokenTransferTransaction{}
	this.TxType = txType
	this.TokenTransfer = tokenTransfer
	return &this
}

// NewTokenTransferTransactionWithDefaults instantiates a new TokenTransferTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTransferTransactionWithDefaults() *TokenTransferTransaction {
	this := TokenTransferTransaction{}
	return &this
}

// GetTxType returns the TxType field value
func (o *TokenTransferTransaction) GetTxType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxType
}

// GetTxTypeOk returns a tuple with the TxType field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransaction) GetTxTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxType, true
}

// SetTxType sets field value
func (o *TokenTransferTransaction) SetTxType(v string) {
	o.TxType = v
}

// GetTokenTransfer returns the TokenTransfer field value
func (o *TokenTransferTransaction) GetTokenTransfer() TokenTransferTransactionMetadataTokenTransfer {
	if o == nil {
		var ret TokenTransferTransactionMetadataTokenTransfer
		return ret
	}

	return o.TokenTransfer
}

// GetTokenTransferOk returns a tuple with the TokenTransfer field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransaction) GetTokenTransferOk() (*TokenTransferTransactionMetadataTokenTransfer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenTransfer, true
}

// SetTokenTransfer sets field value
func (o *TokenTransferTransaction) SetTokenTransfer(v TokenTransferTransactionMetadataTokenTransfer) {
	o.TokenTransfer = v
}

func (o TokenTransferTransaction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tx_type"] = o.TxType
	}
	if true {
		toSerialize["token_transfer"] = o.TokenTransfer
	}
	return json.Marshal(toSerialize)
}

type NullableTokenTransferTransaction struct {
	value *TokenTransferTransaction
	isSet bool
}

func (v NullableTokenTransferTransaction) Get() *TokenTransferTransaction {
	return v.value
}

func (v *NullableTokenTransferTransaction) Set(val *TokenTransferTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTransferTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTransferTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTransferTransaction(val *TokenTransferTransaction) *NullableTokenTransferTransaction {
	return &NullableTokenTransferTransaction{value: val, isSet: true}
}

func (v NullableTokenTransferTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTransferTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


