/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddressAssetsListResponse GET request that returns address assets
type AddressAssetsListResponse struct {
	Limit int32 `json:"limit"`
	Offset int32 `json:"offset"`
	Total int32 `json:"total"`
	Results []Object `json:"results"`
}

// NewAddressAssetsListResponse instantiates a new AddressAssetsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressAssetsListResponse(limit int32, offset int32, total int32, results []Object) *AddressAssetsListResponse {
	this := AddressAssetsListResponse{}
	this.Limit = limit
	this.Offset = offset
	this.Total = total
	this.Results = results
	return &this
}

// NewAddressAssetsListResponseWithDefaults instantiates a new AddressAssetsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressAssetsListResponseWithDefaults() *AddressAssetsListResponse {
	this := AddressAssetsListResponse{}
	return &this
}

// GetLimit returns the Limit field value
func (o *AddressAssetsListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *AddressAssetsListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *AddressAssetsListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *AddressAssetsListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *AddressAssetsListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *AddressAssetsListResponse) SetOffset(v int32) {
	o.Offset = v
}

// GetTotal returns the Total field value
func (o *AddressAssetsListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AddressAssetsListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AddressAssetsListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetResults returns the Results field value
func (o *AddressAssetsListResponse) GetResults() []Object {
	if o == nil {
		var ret []Object
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *AddressAssetsListResponse) GetResultsOk() ([]Object, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *AddressAssetsListResponse) SetResults(v []Object) {
	o.Results = v
}

func (o AddressAssetsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["limit"] = o.Limit
	}
	if true {
		toSerialize["offset"] = o.Offset
	}
	if true {
		toSerialize["total"] = o.Total
	}
	if true {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableAddressAssetsListResponse struct {
	value *AddressAssetsListResponse
	isSet bool
}

func (v NullableAddressAssetsListResponse) Get() *AddressAssetsListResponse {
	return v.value
}

func (v *NullableAddressAssetsListResponse) Set(val *AddressAssetsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressAssetsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressAssetsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressAssetsListResponse(val *AddressAssetsListResponse) *NullableAddressAssetsListResponse {
	return &NullableAddressAssetsListResponse{value: val, isSet: true}
}

func (v NullableAddressAssetsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressAssetsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


