/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BnsFetchFileZoneResponseAnyOf struct for BnsFetchFileZoneResponseAnyOf
type BnsFetchFileZoneResponseAnyOf struct {
	Zonefile *string `json:"zonefile,omitempty"`
}

// NewBnsFetchFileZoneResponseAnyOf instantiates a new BnsFetchFileZoneResponseAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsFetchFileZoneResponseAnyOf() *BnsFetchFileZoneResponseAnyOf {
	this := BnsFetchFileZoneResponseAnyOf{}
	return &this
}

// NewBnsFetchFileZoneResponseAnyOfWithDefaults instantiates a new BnsFetchFileZoneResponseAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsFetchFileZoneResponseAnyOfWithDefaults() *BnsFetchFileZoneResponseAnyOf {
	this := BnsFetchFileZoneResponseAnyOf{}
	return &this
}

// GetZonefile returns the Zonefile field value if set, zero value otherwise.
func (o *BnsFetchFileZoneResponseAnyOf) GetZonefile() string {
	if o == nil || o.Zonefile == nil {
		var ret string
		return ret
	}
	return *o.Zonefile
}

// GetZonefileOk returns a tuple with the Zonefile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BnsFetchFileZoneResponseAnyOf) GetZonefileOk() (*string, bool) {
	if o == nil || o.Zonefile == nil {
		return nil, false
	}
	return o.Zonefile, true
}

// HasZonefile returns a boolean if a field has been set.
func (o *BnsFetchFileZoneResponseAnyOf) HasZonefile() bool {
	if o != nil && o.Zonefile != nil {
		return true
	}

	return false
}

// SetZonefile gets a reference to the given string and assigns it to the Zonefile field.
func (o *BnsFetchFileZoneResponseAnyOf) SetZonefile(v string) {
	o.Zonefile = &v
}

func (o BnsFetchFileZoneResponseAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Zonefile != nil {
		toSerialize["zonefile"] = o.Zonefile
	}
	return json.Marshal(toSerialize)
}

type NullableBnsFetchFileZoneResponseAnyOf struct {
	value *BnsFetchFileZoneResponseAnyOf
	isSet bool
}

func (v NullableBnsFetchFileZoneResponseAnyOf) Get() *BnsFetchFileZoneResponseAnyOf {
	return v.value
}

func (v *NullableBnsFetchFileZoneResponseAnyOf) Set(val *BnsFetchFileZoneResponseAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsFetchFileZoneResponseAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsFetchFileZoneResponseAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsFetchFileZoneResponseAnyOf(val *BnsFetchFileZoneResponseAnyOf) *NullableBnsFetchFileZoneResponseAnyOf {
	return &NullableBnsFetchFileZoneResponseAnyOf{value: val, isSet: true}
}

func (v NullableBnsFetchFileZoneResponseAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsFetchFileZoneResponseAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


