/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaOperationStatus OperationStatus is utilized to indicate which Operation status are considered successful.
type RosettaOperationStatus struct {
	// The status is the network-specific status of the operation.
	Status string `json:"status"`
	// An Operation is considered successful if the Operation.Amount should affect the Operation.Account. Some blockchains (like Bitcoin) only include successful operations in blocks but other blockchains (like Ethereum) include unsuccessful operations that incur a fee. To reconcile the computed balance from the stream of Operations, it is critical to understand which Operation.Status indicate an Operation is successful and should affect an Account.
	Successful bool `json:"successful"`
}

// NewRosettaOperationStatus instantiates a new RosettaOperationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaOperationStatus(status string, successful bool) *RosettaOperationStatus {
	this := RosettaOperationStatus{}
	this.Status = status
	this.Successful = successful
	return &this
}

// NewRosettaOperationStatusWithDefaults instantiates a new RosettaOperationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaOperationStatusWithDefaults() *RosettaOperationStatus {
	this := RosettaOperationStatus{}
	return &this
}

// GetStatus returns the Status field value
func (o *RosettaOperationStatus) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RosettaOperationStatus) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RosettaOperationStatus) SetStatus(v string) {
	o.Status = v
}

// GetSuccessful returns the Successful field value
func (o *RosettaOperationStatus) GetSuccessful() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Successful
}

// GetSuccessfulOk returns a tuple with the Successful field value
// and a boolean to check if the value has been set.
func (o *RosettaOperationStatus) GetSuccessfulOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Successful, true
}

// SetSuccessful sets field value
func (o *RosettaOperationStatus) SetSuccessful(v bool) {
	o.Successful = v
}

func (o RosettaOperationStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["successful"] = o.Successful
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaOperationStatus struct {
	value *RosettaOperationStatus
	isSet bool
}

func (v NullableRosettaOperationStatus) Get() *RosettaOperationStatus {
	return v.value
}

func (v *NullableRosettaOperationStatus) Set(val *RosettaOperationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaOperationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaOperationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaOperationStatus(val *RosettaOperationStatus) *NullableRosettaOperationStatus {
	return &NullableRosettaOperationStatus{value: val, isSet: true}
}

func (v NullableRosettaOperationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaOperationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


