/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaConstructionMetadataRequest A ConstructionMetadataRequest is utilized to get information required to construct a transaction. The Options object used to specify which metadata to return is left purposely unstructured to allow flexibility for implementers. Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
type RosettaConstructionMetadataRequest struct {
	NetworkIdentifier Object `json:"network_identifier"`
	Options RosettaOptions `json:"options"`
	PublicKeys []Object `json:"public_keys,omitempty"`
}

// NewRosettaConstructionMetadataRequest instantiates a new RosettaConstructionMetadataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaConstructionMetadataRequest(networkIdentifier Object, options RosettaOptions) *RosettaConstructionMetadataRequest {
	this := RosettaConstructionMetadataRequest{}
	this.NetworkIdentifier = networkIdentifier
	this.Options = options
	return &this
}

// NewRosettaConstructionMetadataRequestWithDefaults instantiates a new RosettaConstructionMetadataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaConstructionMetadataRequestWithDefaults() *RosettaConstructionMetadataRequest {
	this := RosettaConstructionMetadataRequest{}
	return &this
}

// GetNetworkIdentifier returns the NetworkIdentifier field value
func (o *RosettaConstructionMetadataRequest) GetNetworkIdentifier() Object {
	if o == nil {
		var ret Object
		return ret
	}

	return o.NetworkIdentifier
}

// GetNetworkIdentifierOk returns a tuple with the NetworkIdentifier field value
// and a boolean to check if the value has been set.
func (o *RosettaConstructionMetadataRequest) GetNetworkIdentifierOk() (*Object, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkIdentifier, true
}

// SetNetworkIdentifier sets field value
func (o *RosettaConstructionMetadataRequest) SetNetworkIdentifier(v Object) {
	o.NetworkIdentifier = v
}

// GetOptions returns the Options field value
func (o *RosettaConstructionMetadataRequest) GetOptions() RosettaOptions {
	if o == nil {
		var ret RosettaOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *RosettaConstructionMetadataRequest) GetOptionsOk() (*RosettaOptions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *RosettaConstructionMetadataRequest) SetOptions(v RosettaOptions) {
	o.Options = v
}

// GetPublicKeys returns the PublicKeys field value if set, zero value otherwise.
func (o *RosettaConstructionMetadataRequest) GetPublicKeys() []Object {
	if o == nil || o.PublicKeys == nil {
		var ret []Object
		return ret
	}
	return o.PublicKeys
}

// GetPublicKeysOk returns a tuple with the PublicKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RosettaConstructionMetadataRequest) GetPublicKeysOk() ([]Object, bool) {
	if o == nil || o.PublicKeys == nil {
		return nil, false
	}
	return o.PublicKeys, true
}

// HasPublicKeys returns a boolean if a field has been set.
func (o *RosettaConstructionMetadataRequest) HasPublicKeys() bool {
	if o != nil && o.PublicKeys != nil {
		return true
	}

	return false
}

// SetPublicKeys gets a reference to the given []Object and assigns it to the PublicKeys field.
func (o *RosettaConstructionMetadataRequest) SetPublicKeys(v []Object) {
	o.PublicKeys = v
}

func (o RosettaConstructionMetadataRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["network_identifier"] = o.NetworkIdentifier
	}
	if true {
		toSerialize["options"] = o.Options
	}
	if o.PublicKeys != nil {
		toSerialize["public_keys"] = o.PublicKeys
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaConstructionMetadataRequest struct {
	value *RosettaConstructionMetadataRequest
	isSet bool
}

func (v NullableRosettaConstructionMetadataRequest) Get() *RosettaConstructionMetadataRequest {
	return v.value
}

func (v *NullableRosettaConstructionMetadataRequest) Set(val *RosettaConstructionMetadataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaConstructionMetadataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaConstructionMetadataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaConstructionMetadataRequest(val *RosettaConstructionMetadataRequest) *NullableRosettaConstructionMetadataRequest {
	return &NullableRosettaConstructionMetadataRequest{value: val, isSet: true}
}

func (v NullableRosettaConstructionMetadataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaConstructionMetadataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


