/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionEventStxAsset Only present in `smart_contract` and `contract_call` tx types.
type TransactionEventStxAsset struct {
	EventType string `json:"event_type"`
	TxId string `json:"tx_id"`
	Asset TransactionEventAsset `json:"asset"`
}

// NewTransactionEventStxAsset instantiates a new TransactionEventStxAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionEventStxAsset(eventType string, txId string, asset TransactionEventAsset) *TransactionEventStxAsset {
	this := TransactionEventStxAsset{}
	this.EventType = eventType
	this.TxId = txId
	this.Asset = asset
	return &this
}

// NewTransactionEventStxAssetWithDefaults instantiates a new TransactionEventStxAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionEventStxAssetWithDefaults() *TransactionEventStxAsset {
	this := TransactionEventStxAsset{}
	return &this
}

// GetEventType returns the EventType field value
func (o *TransactionEventStxAsset) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *TransactionEventStxAsset) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *TransactionEventStxAsset) SetEventType(v string) {
	o.EventType = v
}

// GetTxId returns the TxId field value
func (o *TransactionEventStxAsset) GetTxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value
// and a boolean to check if the value has been set.
func (o *TransactionEventStxAsset) GetTxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxId, true
}

// SetTxId sets field value
func (o *TransactionEventStxAsset) SetTxId(v string) {
	o.TxId = v
}

// GetAsset returns the Asset field value
func (o *TransactionEventStxAsset) GetAsset() TransactionEventAsset {
	if o == nil {
		var ret TransactionEventAsset
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *TransactionEventStxAsset) GetAssetOk() (*TransactionEventAsset, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *TransactionEventStxAsset) SetAsset(v TransactionEventAsset) {
	o.Asset = v
}

func (o TransactionEventStxAsset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["event_type"] = o.EventType
	}
	if true {
		toSerialize["tx_id"] = o.TxId
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionEventStxAsset struct {
	value *TransactionEventStxAsset
	isSet bool
}

func (v NullableTransactionEventStxAsset) Get() *TransactionEventStxAsset {
	return v.value
}

func (v *NullableTransactionEventStxAsset) Set(val *TransactionEventStxAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionEventStxAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionEventStxAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionEventStxAsset(val *TransactionEventStxAsset) *NullableTransactionEventStxAsset {
	return &NullableTransactionEventStxAsset{value: val, isSet: true}
}

func (v NullableTransactionEventStxAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionEventStxAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


