/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaMaxFeeAmount Amount is some Value of a Currency. It is considered invalid to specify a Value without a Currency.
type RosettaMaxFeeAmount struct {
	// Value of the transaction in atomic units represented as an arbitrary-sized signed integer. For example, 1 BTC would be represented by a value of 100000000.
	Value string `json:"value"`
	Currency RosettaCurrency `json:"currency"`
	// 
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewRosettaMaxFeeAmount instantiates a new RosettaMaxFeeAmount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaMaxFeeAmount(value string, currency RosettaCurrency) *RosettaMaxFeeAmount {
	this := RosettaMaxFeeAmount{}
	this.Value = value
	this.Currency = currency
	return &this
}

// NewRosettaMaxFeeAmountWithDefaults instantiates a new RosettaMaxFeeAmount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaMaxFeeAmountWithDefaults() *RosettaMaxFeeAmount {
	this := RosettaMaxFeeAmount{}
	return &this
}

// GetValue returns the Value field value
func (o *RosettaMaxFeeAmount) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RosettaMaxFeeAmount) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RosettaMaxFeeAmount) SetValue(v string) {
	o.Value = v
}

// GetCurrency returns the Currency field value
func (o *RosettaMaxFeeAmount) GetCurrency() RosettaCurrency {
	if o == nil {
		var ret RosettaCurrency
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *RosettaMaxFeeAmount) GetCurrencyOk() (*RosettaCurrency, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *RosettaMaxFeeAmount) SetCurrency(v RosettaCurrency) {
	o.Currency = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *RosettaMaxFeeAmount) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RosettaMaxFeeAmount) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RosettaMaxFeeAmount) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *RosettaMaxFeeAmount) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o RosettaMaxFeeAmount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaMaxFeeAmount struct {
	value *RosettaMaxFeeAmount
	isSet bool
}

func (v NullableRosettaMaxFeeAmount) Get() *RosettaMaxFeeAmount {
	return v.value
}

func (v *NullableRosettaMaxFeeAmount) Set(val *RosettaMaxFeeAmount) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaMaxFeeAmount) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaMaxFeeAmount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaMaxFeeAmount(val *RosettaMaxFeeAmount) *NullableRosettaMaxFeeAmount {
	return &NullableRosettaMaxFeeAmount{value: val, isSet: true}
}

func (v NullableRosettaMaxFeeAmount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaMaxFeeAmount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


