/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionEventStxLock Only present in `smart_contract` and `contract_call` tx types.
type TransactionEventStxLock struct {
	EventType string `json:"event_type"`
	TxId string `json:"tx_id"`
	StxLockEvent TransactionEventStxLockAllOfStxLockEvent `json:"stx_lock_event"`
}

// NewTransactionEventStxLock instantiates a new TransactionEventStxLock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionEventStxLock(eventType string, txId string, stxLockEvent TransactionEventStxLockAllOfStxLockEvent) *TransactionEventStxLock {
	this := TransactionEventStxLock{}
	this.EventType = eventType
	this.TxId = txId
	this.StxLockEvent = stxLockEvent
	return &this
}

// NewTransactionEventStxLockWithDefaults instantiates a new TransactionEventStxLock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionEventStxLockWithDefaults() *TransactionEventStxLock {
	this := TransactionEventStxLock{}
	return &this
}

// GetEventType returns the EventType field value
func (o *TransactionEventStxLock) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *TransactionEventStxLock) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *TransactionEventStxLock) SetEventType(v string) {
	o.EventType = v
}

// GetTxId returns the TxId field value
func (o *TransactionEventStxLock) GetTxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value
// and a boolean to check if the value has been set.
func (o *TransactionEventStxLock) GetTxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxId, true
}

// SetTxId sets field value
func (o *TransactionEventStxLock) SetTxId(v string) {
	o.TxId = v
}

// GetStxLockEvent returns the StxLockEvent field value
func (o *TransactionEventStxLock) GetStxLockEvent() TransactionEventStxLockAllOfStxLockEvent {
	if o == nil {
		var ret TransactionEventStxLockAllOfStxLockEvent
		return ret
	}

	return o.StxLockEvent
}

// GetStxLockEventOk returns a tuple with the StxLockEvent field value
// and a boolean to check if the value has been set.
func (o *TransactionEventStxLock) GetStxLockEventOk() (*TransactionEventStxLockAllOfStxLockEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StxLockEvent, true
}

// SetStxLockEvent sets field value
func (o *TransactionEventStxLock) SetStxLockEvent(v TransactionEventStxLockAllOfStxLockEvent) {
	o.StxLockEvent = v
}

func (o TransactionEventStxLock) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["event_type"] = o.EventType
	}
	if true {
		toSerialize["tx_id"] = o.TxId
	}
	if true {
		toSerialize["stx_lock_event"] = o.StxLockEvent
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionEventStxLock struct {
	value *TransactionEventStxLock
	isSet bool
}

func (v NullableTransactionEventStxLock) Get() *TransactionEventStxLock {
	return v.value
}

func (v *NullableTransactionEventStxLock) Set(val *TransactionEventStxLock) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionEventStxLock) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionEventStxLock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionEventStxLock(val *TransactionEventStxLock) *NullableTransactionEventStxLock {
	return &NullableTransactionEventStxLock{value: val, isSet: true}
}

func (v NullableTransactionEventStxLock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionEventStxLock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


