/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddressStxBalanceResponseAllOf struct for AddressStxBalanceResponseAllOf
type AddressStxBalanceResponseAllOf struct {
	TokenOfferingLocked *Object `json:"token_offering_locked,omitempty"`
}

// NewAddressStxBalanceResponseAllOf instantiates a new AddressStxBalanceResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressStxBalanceResponseAllOf() *AddressStxBalanceResponseAllOf {
	this := AddressStxBalanceResponseAllOf{}
	return &this
}

// NewAddressStxBalanceResponseAllOfWithDefaults instantiates a new AddressStxBalanceResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressStxBalanceResponseAllOfWithDefaults() *AddressStxBalanceResponseAllOf {
	this := AddressStxBalanceResponseAllOf{}
	return &this
}

// GetTokenOfferingLocked returns the TokenOfferingLocked field value if set, zero value otherwise.
func (o *AddressStxBalanceResponseAllOf) GetTokenOfferingLocked() Object {
	if o == nil || o.TokenOfferingLocked == nil {
		var ret Object
		return ret
	}
	return *o.TokenOfferingLocked
}

// GetTokenOfferingLockedOk returns a tuple with the TokenOfferingLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressStxBalanceResponseAllOf) GetTokenOfferingLockedOk() (*Object, bool) {
	if o == nil || o.TokenOfferingLocked == nil {
		return nil, false
	}
	return o.TokenOfferingLocked, true
}

// HasTokenOfferingLocked returns a boolean if a field has been set.
func (o *AddressStxBalanceResponseAllOf) HasTokenOfferingLocked() bool {
	if o != nil && o.TokenOfferingLocked != nil {
		return true
	}

	return false
}

// SetTokenOfferingLocked gets a reference to the given Object and assigns it to the TokenOfferingLocked field.
func (o *AddressStxBalanceResponseAllOf) SetTokenOfferingLocked(v Object) {
	o.TokenOfferingLocked = &v
}

func (o AddressStxBalanceResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TokenOfferingLocked != nil {
		toSerialize["token_offering_locked"] = o.TokenOfferingLocked
	}
	return json.Marshal(toSerialize)
}

type NullableAddressStxBalanceResponseAllOf struct {
	value *AddressStxBalanceResponseAllOf
	isSet bool
}

func (v NullableAddressStxBalanceResponseAllOf) Get() *AddressStxBalanceResponseAllOf {
	return v.value
}

func (v *NullableAddressStxBalanceResponseAllOf) Set(val *AddressStxBalanceResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressStxBalanceResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressStxBalanceResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressStxBalanceResponseAllOf(val *AddressStxBalanceResponseAllOf) *NullableAddressStxBalanceResponseAllOf {
	return &NullableAddressStxBalanceResponseAllOf{value: val, isSet: true}
}

func (v NullableAddressStxBalanceResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressStxBalanceResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


