/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RunFaucetStxRequest struct for RunFaucetStxRequest
type RunFaucetStxRequest struct {
	// STX testnet address
	Address *string `json:"address,omitempty"`
	// Use required number of tokens for stacking
	Stacking *bool `json:"stacking,omitempty"`
}

// NewRunFaucetStxRequest instantiates a new RunFaucetStxRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunFaucetStxRequest() *RunFaucetStxRequest {
	this := RunFaucetStxRequest{}
	return &this
}

// NewRunFaucetStxRequestWithDefaults instantiates a new RunFaucetStxRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunFaucetStxRequestWithDefaults() *RunFaucetStxRequest {
	this := RunFaucetStxRequest{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *RunFaucetStxRequest) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunFaucetStxRequest) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *RunFaucetStxRequest) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *RunFaucetStxRequest) SetAddress(v string) {
	o.Address = &v
}

// GetStacking returns the Stacking field value if set, zero value otherwise.
func (o *RunFaucetStxRequest) GetStacking() bool {
	if o == nil || o.Stacking == nil {
		var ret bool
		return ret
	}
	return *o.Stacking
}

// GetStackingOk returns a tuple with the Stacking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunFaucetStxRequest) GetStackingOk() (*bool, bool) {
	if o == nil || o.Stacking == nil {
		return nil, false
	}
	return o.Stacking, true
}

// HasStacking returns a boolean if a field has been set.
func (o *RunFaucetStxRequest) HasStacking() bool {
	if o != nil && o.Stacking != nil {
		return true
	}

	return false
}

// SetStacking gets a reference to the given bool and assigns it to the Stacking field.
func (o *RunFaucetStxRequest) SetStacking(v bool) {
	o.Stacking = &v
}

func (o RunFaucetStxRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Stacking != nil {
		toSerialize["stacking"] = o.Stacking
	}
	return json.Marshal(toSerialize)
}

type NullableRunFaucetStxRequest struct {
	value *RunFaucetStxRequest
	isSet bool
}

func (v NullableRunFaucetStxRequest) Get() *RunFaucetStxRequest {
	return v.value
}

func (v *NullableRunFaucetStxRequest) Set(val *RunFaucetStxRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRunFaucetStxRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRunFaucetStxRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunFaucetStxRequest(val *RunFaucetStxRequest) *NullableRunFaucetStxRequest {
	return &NullableRunFaucetStxRequest{value: val, isSet: true}
}

func (v NullableRunFaucetStxRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunFaucetStxRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


