/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddressTransactionWithTransfersNftTransfersInner struct for AddressTransactionWithTransfersNftTransfersInner
type AddressTransactionWithTransfersNftTransfersInner struct {
	// Non Fungible Token asset identifier.
	AssetIdentifier string `json:"asset_identifier"`
	Value AddressTransactionWithTransfersNftTransfersInnerValue `json:"value"`
	// Principal that sent the asset.
	Sender *string `json:"sender,omitempty"`
	// Principal that received the asset.
	Recipient *string `json:"recipient,omitempty"`
}

// NewAddressTransactionWithTransfersNftTransfersInner instantiates a new AddressTransactionWithTransfersNftTransfersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressTransactionWithTransfersNftTransfersInner(assetIdentifier string, value AddressTransactionWithTransfersNftTransfersInnerValue) *AddressTransactionWithTransfersNftTransfersInner {
	this := AddressTransactionWithTransfersNftTransfersInner{}
	this.AssetIdentifier = assetIdentifier
	this.Value = value
	return &this
}

// NewAddressTransactionWithTransfersNftTransfersInnerWithDefaults instantiates a new AddressTransactionWithTransfersNftTransfersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressTransactionWithTransfersNftTransfersInnerWithDefaults() *AddressTransactionWithTransfersNftTransfersInner {
	this := AddressTransactionWithTransfersNftTransfersInner{}
	return &this
}

// GetAssetIdentifier returns the AssetIdentifier field value
func (o *AddressTransactionWithTransfersNftTransfersInner) GetAssetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetIdentifier
}

// GetAssetIdentifierOk returns a tuple with the AssetIdentifier field value
// and a boolean to check if the value has been set.
func (o *AddressTransactionWithTransfersNftTransfersInner) GetAssetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetIdentifier, true
}

// SetAssetIdentifier sets field value
func (o *AddressTransactionWithTransfersNftTransfersInner) SetAssetIdentifier(v string) {
	o.AssetIdentifier = v
}

// GetValue returns the Value field value
func (o *AddressTransactionWithTransfersNftTransfersInner) GetValue() AddressTransactionWithTransfersNftTransfersInnerValue {
	if o == nil {
		var ret AddressTransactionWithTransfersNftTransfersInnerValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AddressTransactionWithTransfersNftTransfersInner) GetValueOk() (*AddressTransactionWithTransfersNftTransfersInnerValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AddressTransactionWithTransfersNftTransfersInner) SetValue(v AddressTransactionWithTransfersNftTransfersInnerValue) {
	o.Value = v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *AddressTransactionWithTransfersNftTransfersInner) GetSender() string {
	if o == nil || o.Sender == nil {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTransactionWithTransfersNftTransfersInner) GetSenderOk() (*string, bool) {
	if o == nil || o.Sender == nil {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *AddressTransactionWithTransfersNftTransfersInner) HasSender() bool {
	if o != nil && o.Sender != nil {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *AddressTransactionWithTransfersNftTransfersInner) SetSender(v string) {
	o.Sender = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *AddressTransactionWithTransfersNftTransfersInner) GetRecipient() string {
	if o == nil || o.Recipient == nil {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTransactionWithTransfersNftTransfersInner) GetRecipientOk() (*string, bool) {
	if o == nil || o.Recipient == nil {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *AddressTransactionWithTransfersNftTransfersInner) HasRecipient() bool {
	if o != nil && o.Recipient != nil {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *AddressTransactionWithTransfersNftTransfersInner) SetRecipient(v string) {
	o.Recipient = &v
}

func (o AddressTransactionWithTransfersNftTransfersInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset_identifier"] = o.AssetIdentifier
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if o.Sender != nil {
		toSerialize["sender"] = o.Sender
	}
	if o.Recipient != nil {
		toSerialize["recipient"] = o.Recipient
	}
	return json.Marshal(toSerialize)
}

type NullableAddressTransactionWithTransfersNftTransfersInner struct {
	value *AddressTransactionWithTransfersNftTransfersInner
	isSet bool
}

func (v NullableAddressTransactionWithTransfersNftTransfersInner) Get() *AddressTransactionWithTransfersNftTransfersInner {
	return v.value
}

func (v *NullableAddressTransactionWithTransfersNftTransfersInner) Set(val *AddressTransactionWithTransfersNftTransfersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressTransactionWithTransfersNftTransfersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressTransactionWithTransfersNftTransfersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressTransactionWithTransfersNftTransfersInner(val *AddressTransactionWithTransfersNftTransfersInner) *NullableAddressTransactionWithTransfersNftTransfersInner {
	return &NullableAddressTransactionWithTransfersNftTransfersInner{value: val, isSet: true}
}

func (v NullableAddressTransactionWithTransfersNftTransfersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressTransactionWithTransfersNftTransfersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


