/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaAccountBalanceResponseMetadata Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address.
type RosettaAccountBalanceResponseMetadata struct {
	SequenceNumber int32 `json:"sequence_number"`
}

// NewRosettaAccountBalanceResponseMetadata instantiates a new RosettaAccountBalanceResponseMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaAccountBalanceResponseMetadata(sequenceNumber int32) *RosettaAccountBalanceResponseMetadata {
	this := RosettaAccountBalanceResponseMetadata{}
	this.SequenceNumber = sequenceNumber
	return &this
}

// NewRosettaAccountBalanceResponseMetadataWithDefaults instantiates a new RosettaAccountBalanceResponseMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaAccountBalanceResponseMetadataWithDefaults() *RosettaAccountBalanceResponseMetadata {
	this := RosettaAccountBalanceResponseMetadata{}
	return &this
}

// GetSequenceNumber returns the SequenceNumber field value
func (o *RosettaAccountBalanceResponseMetadata) GetSequenceNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SequenceNumber
}

// GetSequenceNumberOk returns a tuple with the SequenceNumber field value
// and a boolean to check if the value has been set.
func (o *RosettaAccountBalanceResponseMetadata) GetSequenceNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SequenceNumber, true
}

// SetSequenceNumber sets field value
func (o *RosettaAccountBalanceResponseMetadata) SetSequenceNumber(v int32) {
	o.SequenceNumber = v
}

func (o RosettaAccountBalanceResponseMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sequence_number"] = o.SequenceNumber
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaAccountBalanceResponseMetadata struct {
	value *RosettaAccountBalanceResponseMetadata
	isSet bool
}

func (v NullableRosettaAccountBalanceResponseMetadata) Get() *RosettaAccountBalanceResponseMetadata {
	return v.value
}

func (v *NullableRosettaAccountBalanceResponseMetadata) Set(val *RosettaAccountBalanceResponseMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaAccountBalanceResponseMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaAccountBalanceResponseMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaAccountBalanceResponseMetadata(val *RosettaAccountBalanceResponseMetadata) *NullableRosettaAccountBalanceResponseMetadata {
	return &NullableRosettaAccountBalanceResponseMetadata{value: val, isSet: true}
}

func (v NullableRosettaAccountBalanceResponseMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaAccountBalanceResponseMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


