/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// NonFungibleTokenMintWithTxId Non-Fungible Token mint event with transaction id
type NonFungibleTokenMintWithTxId struct {
	Recipient *string `json:"recipient,omitempty"`
	EventIndex int32 `json:"event_index"`
	Value NonFungibleTokenHoldingWithTxIdValue `json:"value"`
	TxId string `json:"tx_id"`
}

// NewNonFungibleTokenMintWithTxId instantiates a new NonFungibleTokenMintWithTxId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNonFungibleTokenMintWithTxId(eventIndex int32, value NonFungibleTokenHoldingWithTxIdValue, txId string) *NonFungibleTokenMintWithTxId {
	this := NonFungibleTokenMintWithTxId{}
	this.EventIndex = eventIndex
	this.Value = value
	this.TxId = txId
	return &this
}

// NewNonFungibleTokenMintWithTxIdWithDefaults instantiates a new NonFungibleTokenMintWithTxId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNonFungibleTokenMintWithTxIdWithDefaults() *NonFungibleTokenMintWithTxId {
	this := NonFungibleTokenMintWithTxId{}
	return &this
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *NonFungibleTokenMintWithTxId) GetRecipient() string {
	if o == nil || o.Recipient == nil {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxId) GetRecipientOk() (*string, bool) {
	if o == nil || o.Recipient == nil {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *NonFungibleTokenMintWithTxId) HasRecipient() bool {
	if o != nil && o.Recipient != nil {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *NonFungibleTokenMintWithTxId) SetRecipient(v string) {
	o.Recipient = &v
}

// GetEventIndex returns the EventIndex field value
func (o *NonFungibleTokenMintWithTxId) GetEventIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventIndex
}

// GetEventIndexOk returns a tuple with the EventIndex field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxId) GetEventIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventIndex, true
}

// SetEventIndex sets field value
func (o *NonFungibleTokenMintWithTxId) SetEventIndex(v int32) {
	o.EventIndex = v
}

// GetValue returns the Value field value
func (o *NonFungibleTokenMintWithTxId) GetValue() NonFungibleTokenHoldingWithTxIdValue {
	if o == nil {
		var ret NonFungibleTokenHoldingWithTxIdValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxId) GetValueOk() (*NonFungibleTokenHoldingWithTxIdValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NonFungibleTokenMintWithTxId) SetValue(v NonFungibleTokenHoldingWithTxIdValue) {
	o.Value = v
}

// GetTxId returns the TxId field value
func (o *NonFungibleTokenMintWithTxId) GetTxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxId) GetTxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxId, true
}

// SetTxId sets field value
func (o *NonFungibleTokenMintWithTxId) SetTxId(v string) {
	o.TxId = v
}

func (o NonFungibleTokenMintWithTxId) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Recipient != nil {
		toSerialize["recipient"] = o.Recipient
	}
	if true {
		toSerialize["event_index"] = o.EventIndex
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["tx_id"] = o.TxId
	}
	return json.Marshal(toSerialize)
}

type NullableNonFungibleTokenMintWithTxId struct {
	value *NonFungibleTokenMintWithTxId
	isSet bool
}

func (v NullableNonFungibleTokenMintWithTxId) Get() *NonFungibleTokenMintWithTxId {
	return v.value
}

func (v *NullableNonFungibleTokenMintWithTxId) Set(val *NonFungibleTokenMintWithTxId) {
	v.value = val
	v.isSet = true
}

func (v NullableNonFungibleTokenMintWithTxId) IsSet() bool {
	return v.isSet
}

func (v *NullableNonFungibleTokenMintWithTxId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNonFungibleTokenMintWithTxId(val *NonFungibleTokenMintWithTxId) *NullableNonFungibleTokenMintWithTxId {
	return &NullableNonFungibleTokenMintWithTxId{value: val, isSet: true}
}

func (v NullableNonFungibleTokenMintWithTxId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNonFungibleTokenMintWithTxId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


