/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// NonFungibleTokenMintWithTxMetadata Non-Fungible Token mint event with transaction metadata
type NonFungibleTokenMintWithTxMetadata struct {
	Recipient *string `json:"recipient,omitempty"`
	EventIndex int32 `json:"event_index"`
	Value NonFungibleTokenHoldingWithTxIdValue `json:"value"`
	Tx Object `json:"tx"`
}

// NewNonFungibleTokenMintWithTxMetadata instantiates a new NonFungibleTokenMintWithTxMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNonFungibleTokenMintWithTxMetadata(eventIndex int32, value NonFungibleTokenHoldingWithTxIdValue, tx Object) *NonFungibleTokenMintWithTxMetadata {
	this := NonFungibleTokenMintWithTxMetadata{}
	this.EventIndex = eventIndex
	this.Value = value
	this.Tx = tx
	return &this
}

// NewNonFungibleTokenMintWithTxMetadataWithDefaults instantiates a new NonFungibleTokenMintWithTxMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNonFungibleTokenMintWithTxMetadataWithDefaults() *NonFungibleTokenMintWithTxMetadata {
	this := NonFungibleTokenMintWithTxMetadata{}
	return &this
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *NonFungibleTokenMintWithTxMetadata) GetRecipient() string {
	if o == nil || o.Recipient == nil {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxMetadata) GetRecipientOk() (*string, bool) {
	if o == nil || o.Recipient == nil {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *NonFungibleTokenMintWithTxMetadata) HasRecipient() bool {
	if o != nil && o.Recipient != nil {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *NonFungibleTokenMintWithTxMetadata) SetRecipient(v string) {
	o.Recipient = &v
}

// GetEventIndex returns the EventIndex field value
func (o *NonFungibleTokenMintWithTxMetadata) GetEventIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventIndex
}

// GetEventIndexOk returns a tuple with the EventIndex field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxMetadata) GetEventIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventIndex, true
}

// SetEventIndex sets field value
func (o *NonFungibleTokenMintWithTxMetadata) SetEventIndex(v int32) {
	o.EventIndex = v
}

// GetValue returns the Value field value
func (o *NonFungibleTokenMintWithTxMetadata) GetValue() NonFungibleTokenHoldingWithTxIdValue {
	if o == nil {
		var ret NonFungibleTokenHoldingWithTxIdValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxMetadata) GetValueOk() (*NonFungibleTokenHoldingWithTxIdValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NonFungibleTokenMintWithTxMetadata) SetValue(v NonFungibleTokenHoldingWithTxIdValue) {
	o.Value = v
}

// GetTx returns the Tx field value
func (o *NonFungibleTokenMintWithTxMetadata) GetTx() Object {
	if o == nil {
		var ret Object
		return ret
	}

	return o.Tx
}

// GetTxOk returns a tuple with the Tx field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenMintWithTxMetadata) GetTxOk() (*Object, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tx, true
}

// SetTx sets field value
func (o *NonFungibleTokenMintWithTxMetadata) SetTx(v Object) {
	o.Tx = v
}

func (o NonFungibleTokenMintWithTxMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Recipient != nil {
		toSerialize["recipient"] = o.Recipient
	}
	if true {
		toSerialize["event_index"] = o.EventIndex
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["tx"] = o.Tx
	}
	return json.Marshal(toSerialize)
}

type NullableNonFungibleTokenMintWithTxMetadata struct {
	value *NonFungibleTokenMintWithTxMetadata
	isSet bool
}

func (v NullableNonFungibleTokenMintWithTxMetadata) Get() *NonFungibleTokenMintWithTxMetadata {
	return v.value
}

func (v *NullableNonFungibleTokenMintWithTxMetadata) Set(val *NonFungibleTokenMintWithTxMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableNonFungibleTokenMintWithTxMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableNonFungibleTokenMintWithTxMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNonFungibleTokenMintWithTxMetadata(val *NonFungibleTokenMintWithTxMetadata) *NullableNonFungibleTokenMintWithTxMetadata {
	return &NullableNonFungibleTokenMintWithTxMetadata{value: val, isSet: true}
}

func (v NullableNonFungibleTokenMintWithTxMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNonFungibleTokenMintWithTxMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


