/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: STACKS_API_VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RosettaNetworkOptionsResponseAllowOperationTypesInner struct for RosettaNetworkOptionsResponseAllowOperationTypesInner
type RosettaNetworkOptionsResponseAllowOperationTypesInner struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RosettaNetworkOptionsResponseAllowOperationTypesInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(RosettaNetworkOptionsResponseAllowOperationTypesInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *RosettaNetworkOptionsResponseAllowOperationTypesInner) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableRosettaNetworkOptionsResponseAllowOperationTypesInner struct {
	value *RosettaNetworkOptionsResponseAllowOperationTypesInner
	isSet bool
}

func (v NullableRosettaNetworkOptionsResponseAllowOperationTypesInner) Get() *RosettaNetworkOptionsResponseAllowOperationTypesInner {
	return v.value
}

func (v *NullableRosettaNetworkOptionsResponseAllowOperationTypesInner) Set(val *RosettaNetworkOptionsResponseAllowOperationTypesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaNetworkOptionsResponseAllowOperationTypesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaNetworkOptionsResponseAllowOperationTypesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaNetworkOptionsResponseAllowOperationTypesInner(val *RosettaNetworkOptionsResponseAllowOperationTypesInner) *NullableRosettaNetworkOptionsResponseAllowOperationTypesInner {
	return &NullableRosettaNetworkOptionsResponseAllowOperationTypesInner{value: val, isSet: true}
}

func (v NullableRosettaNetworkOptionsResponseAllowOperationTypesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaNetworkOptionsResponseAllowOperationTypesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


