/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionEventNonFungibleAssetAllOfAsset struct for TransactionEventNonFungibleAssetAllOfAsset
type TransactionEventNonFungibleAssetAllOfAsset struct {
	AssetEventType string `json:"asset_event_type"`
	AssetId string `json:"asset_id"`
	Sender string `json:"sender"`
	Recipient string `json:"recipient"`
	Value PostConditionNonFungibleAllOfAssetValue `json:"value"`
}

// NewTransactionEventNonFungibleAssetAllOfAsset instantiates a new TransactionEventNonFungibleAssetAllOfAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionEventNonFungibleAssetAllOfAsset(assetEventType string, assetId string, sender string, recipient string, value PostConditionNonFungibleAllOfAssetValue) *TransactionEventNonFungibleAssetAllOfAsset {
	this := TransactionEventNonFungibleAssetAllOfAsset{}
	this.AssetEventType = assetEventType
	this.AssetId = assetId
	this.Sender = sender
	this.Recipient = recipient
	this.Value = value
	return &this
}

// NewTransactionEventNonFungibleAssetAllOfAssetWithDefaults instantiates a new TransactionEventNonFungibleAssetAllOfAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionEventNonFungibleAssetAllOfAssetWithDefaults() *TransactionEventNonFungibleAssetAllOfAsset {
	this := TransactionEventNonFungibleAssetAllOfAsset{}
	return &this
}

// GetAssetEventType returns the AssetEventType field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetAssetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetEventType
}

// GetAssetEventTypeOk returns a tuple with the AssetEventType field value
// and a boolean to check if the value has been set.
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetAssetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetEventType, true
}

// SetAssetEventType sets field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) SetAssetEventType(v string) {
	o.AssetEventType = v
}

// GetAssetId returns the AssetId field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) SetAssetId(v string) {
	o.AssetId = v
}

// GetSender returns the Sender field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) SetSender(v string) {
	o.Sender = v
}

// GetRecipient returns the Recipient field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) SetRecipient(v string) {
	o.Recipient = v
}

// GetValue returns the Value field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetValue() PostConditionNonFungibleAllOfAssetValue {
	if o == nil {
		var ret PostConditionNonFungibleAllOfAssetValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *TransactionEventNonFungibleAssetAllOfAsset) GetValueOk() (*PostConditionNonFungibleAllOfAssetValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *TransactionEventNonFungibleAssetAllOfAsset) SetValue(v PostConditionNonFungibleAllOfAssetValue) {
	o.Value = v
}

func (o TransactionEventNonFungibleAssetAllOfAsset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset_event_type"] = o.AssetEventType
	}
	if true {
		toSerialize["asset_id"] = o.AssetId
	}
	if true {
		toSerialize["sender"] = o.Sender
	}
	if true {
		toSerialize["recipient"] = o.Recipient
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionEventNonFungibleAssetAllOfAsset struct {
	value *TransactionEventNonFungibleAssetAllOfAsset
	isSet bool
}

func (v NullableTransactionEventNonFungibleAssetAllOfAsset) Get() *TransactionEventNonFungibleAssetAllOfAsset {
	return v.value
}

func (v *NullableTransactionEventNonFungibleAssetAllOfAsset) Set(val *TransactionEventNonFungibleAssetAllOfAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionEventNonFungibleAssetAllOfAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionEventNonFungibleAssetAllOfAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionEventNonFungibleAssetAllOfAsset(val *TransactionEventNonFungibleAssetAllOfAsset) *NullableTransactionEventNonFungibleAssetAllOfAsset {
	return &NullableTransactionEventNonFungibleAssetAllOfAsset{value: val, isSet: true}
}

func (v NullableTransactionEventNonFungibleAssetAllOfAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionEventNonFungibleAssetAllOfAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


