/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetStxSupplyResponse GET request that returns network target block times
type GetStxSupplyResponse struct {
	// String quoted decimal number of the percentage of STX that have unlocked
	UnlockedPercent string `json:"unlocked_percent"`
	// String quoted decimal number of the total possible number of STX
	TotalSTX string `json:"total_STX"`
	// String quoted decimal number of the STX that have been mined or unlocked
	UnlockedSTX string `json:"unlocked_STX"`
	// The block height at which this information was queried
	BlockHeight int32 `json:"block_height"`
}

// NewGetStxSupplyResponse instantiates a new GetStxSupplyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStxSupplyResponse(unlockedPercent string, totalSTX string, unlockedSTX string, blockHeight int32) *GetStxSupplyResponse {
	this := GetStxSupplyResponse{}
	this.UnlockedPercent = unlockedPercent
	this.TotalSTX = totalSTX
	this.UnlockedSTX = unlockedSTX
	this.BlockHeight = blockHeight
	return &this
}

// NewGetStxSupplyResponseWithDefaults instantiates a new GetStxSupplyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStxSupplyResponseWithDefaults() *GetStxSupplyResponse {
	this := GetStxSupplyResponse{}
	return &this
}

// GetUnlockedPercent returns the UnlockedPercent field value
func (o *GetStxSupplyResponse) GetUnlockedPercent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnlockedPercent
}

// GetUnlockedPercentOk returns a tuple with the UnlockedPercent field value
// and a boolean to check if the value has been set.
func (o *GetStxSupplyResponse) GetUnlockedPercentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnlockedPercent, true
}

// SetUnlockedPercent sets field value
func (o *GetStxSupplyResponse) SetUnlockedPercent(v string) {
	o.UnlockedPercent = v
}

// GetTotalSTX returns the TotalSTX field value
func (o *GetStxSupplyResponse) GetTotalSTX() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TotalSTX
}

// GetTotalSTXOk returns a tuple with the TotalSTX field value
// and a boolean to check if the value has been set.
func (o *GetStxSupplyResponse) GetTotalSTXOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSTX, true
}

// SetTotalSTX sets field value
func (o *GetStxSupplyResponse) SetTotalSTX(v string) {
	o.TotalSTX = v
}

// GetUnlockedSTX returns the UnlockedSTX field value
func (o *GetStxSupplyResponse) GetUnlockedSTX() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnlockedSTX
}

// GetUnlockedSTXOk returns a tuple with the UnlockedSTX field value
// and a boolean to check if the value has been set.
func (o *GetStxSupplyResponse) GetUnlockedSTXOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnlockedSTX, true
}

// SetUnlockedSTX sets field value
func (o *GetStxSupplyResponse) SetUnlockedSTX(v string) {
	o.UnlockedSTX = v
}

// GetBlockHeight returns the BlockHeight field value
func (o *GetStxSupplyResponse) GetBlockHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockHeight
}

// GetBlockHeightOk returns a tuple with the BlockHeight field value
// and a boolean to check if the value has been set.
func (o *GetStxSupplyResponse) GetBlockHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockHeight, true
}

// SetBlockHeight sets field value
func (o *GetStxSupplyResponse) SetBlockHeight(v int32) {
	o.BlockHeight = v
}

func (o GetStxSupplyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["unlocked_percent"] = o.UnlockedPercent
	}
	if true {
		toSerialize["total_STX"] = o.TotalSTX
	}
	if true {
		toSerialize["unlocked_STX"] = o.UnlockedSTX
	}
	if true {
		toSerialize["block_height"] = o.BlockHeight
	}
	return json.Marshal(toSerialize)
}

type NullableGetStxSupplyResponse struct {
	value *GetStxSupplyResponse
	isSet bool
}

func (v NullableGetStxSupplyResponse) Get() *GetStxSupplyResponse {
	return v.value
}

func (v *NullableGetStxSupplyResponse) Set(val *GetStxSupplyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStxSupplyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStxSupplyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStxSupplyResponse(val *GetStxSupplyResponse) *NullableGetStxSupplyResponse {
	return &NullableGetStxSupplyResponse{value: val, isSet: true}
}

func (v NullableGetStxSupplyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStxSupplyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


