/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddressTransactionWithTransfersNFTTransfersInnerValue Non Fungible Token asset value.
type AddressTransactionWithTransfersNFTTransfersInnerValue struct {
	Hex string `json:"hex"`
	Repr string `json:"repr"`
}

// NewAddressTransactionWithTransfersNFTTransfersInnerValue instantiates a new AddressTransactionWithTransfersNFTTransfersInnerValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressTransactionWithTransfersNFTTransfersInnerValue(hex string, repr string) *AddressTransactionWithTransfersNFTTransfersInnerValue {
	this := AddressTransactionWithTransfersNFTTransfersInnerValue{}
	this.Hex = hex
	this.Repr = repr
	return &this
}

// NewAddressTransactionWithTransfersNFTTransfersInnerValueWithDefaults instantiates a new AddressTransactionWithTransfersNFTTransfersInnerValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressTransactionWithTransfersNFTTransfersInnerValueWithDefaults() *AddressTransactionWithTransfersNFTTransfersInnerValue {
	this := AddressTransactionWithTransfersNFTTransfersInnerValue{}
	return &this
}

// GetHex returns the Hex field value
func (o *AddressTransactionWithTransfersNFTTransfersInnerValue) GetHex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hex
}

// GetHexOk returns a tuple with the Hex field value
// and a boolean to check if the value has been set.
func (o *AddressTransactionWithTransfersNFTTransfersInnerValue) GetHexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hex, true
}

// SetHex sets field value
func (o *AddressTransactionWithTransfersNFTTransfersInnerValue) SetHex(v string) {
	o.Hex = v
}

// GetRepr returns the Repr field value
func (o *AddressTransactionWithTransfersNFTTransfersInnerValue) GetRepr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repr
}

// GetReprOk returns a tuple with the Repr field value
// and a boolean to check if the value has been set.
func (o *AddressTransactionWithTransfersNFTTransfersInnerValue) GetReprOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repr, true
}

// SetRepr sets field value
func (o *AddressTransactionWithTransfersNFTTransfersInnerValue) SetRepr(v string) {
	o.Repr = v
}

func (o AddressTransactionWithTransfersNFTTransfersInnerValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hex"] = o.Hex
	}
	if true {
		toSerialize["repr"] = o.Repr
	}
	return json.Marshal(toSerialize)
}

type NullableAddressTransactionWithTransfersNFTTransfersInnerValue struct {
	value *AddressTransactionWithTransfersNFTTransfersInnerValue
	isSet bool
}

func (v NullableAddressTransactionWithTransfersNFTTransfersInnerValue) Get() *AddressTransactionWithTransfersNFTTransfersInnerValue {
	return v.value
}

func (v *NullableAddressTransactionWithTransfersNFTTransfersInnerValue) Set(val *AddressTransactionWithTransfersNFTTransfersInnerValue) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressTransactionWithTransfersNFTTransfersInnerValue) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressTransactionWithTransfersNFTTransfersInnerValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressTransactionWithTransfersNFTTransfersInnerValue(val *AddressTransactionWithTransfersNFTTransfersInnerValue) *NullableAddressTransactionWithTransfersNFTTransfersInnerValue {
	return &NullableAddressTransactionWithTransfersNFTTransfersInnerValue{value: val, isSet: true}
}

func (v NullableAddressTransactionWithTransfersNFTTransfersInnerValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressTransactionWithTransfersNFTTransfersInnerValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


