/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaAccountBalanceResponse An AccountBalanceResponse is returned on the /account/balance endpoint. If an account has a balance for each AccountIdentifier describing it (ex: an ERC-20 token balance on a few smart contracts), an account balance request must be made with each AccountIdentifier.
type RosettaAccountBalanceResponse struct {
	BlockIdentifier RosettaBlockIdentifier `json:"block_identifier"`
	// A single account balance may have multiple currencies
	Balances []RosettaAmount `json:"balances"`
	// If a blockchain is UTXO-based, all unspent Coins owned by an account_identifier should be returned alongside the balance. It is highly recommended to populate this field so that users of the Rosetta API implementation don't need to maintain their own indexer to track their UTXOs.
	Coins []RosettaCoin `json:"coins,omitempty"`
	Metadata *RosettaAccountBalanceResponseMetadata `json:"metadata,omitempty"`
}

// NewRosettaAccountBalanceResponse instantiates a new RosettaAccountBalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaAccountBalanceResponse(blockIdentifier RosettaBlockIdentifier, balances []RosettaAmount) *RosettaAccountBalanceResponse {
	this := RosettaAccountBalanceResponse{}
	this.BlockIdentifier = blockIdentifier
	this.Balances = balances
	return &this
}

// NewRosettaAccountBalanceResponseWithDefaults instantiates a new RosettaAccountBalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaAccountBalanceResponseWithDefaults() *RosettaAccountBalanceResponse {
	this := RosettaAccountBalanceResponse{}
	return &this
}

// GetBlockIdentifier returns the BlockIdentifier field value
func (o *RosettaAccountBalanceResponse) GetBlockIdentifier() RosettaBlockIdentifier {
	if o == nil {
		var ret RosettaBlockIdentifier
		return ret
	}

	return o.BlockIdentifier
}

// GetBlockIdentifierOk returns a tuple with the BlockIdentifier field value
// and a boolean to check if the value has been set.
func (o *RosettaAccountBalanceResponse) GetBlockIdentifierOk() (*RosettaBlockIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockIdentifier, true
}

// SetBlockIdentifier sets field value
func (o *RosettaAccountBalanceResponse) SetBlockIdentifier(v RosettaBlockIdentifier) {
	o.BlockIdentifier = v
}

// GetBalances returns the Balances field value
func (o *RosettaAccountBalanceResponse) GetBalances() []RosettaAmount {
	if o == nil {
		var ret []RosettaAmount
		return ret
	}

	return o.Balances
}

// GetBalancesOk returns a tuple with the Balances field value
// and a boolean to check if the value has been set.
func (o *RosettaAccountBalanceResponse) GetBalancesOk() ([]RosettaAmount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Balances, true
}

// SetBalances sets field value
func (o *RosettaAccountBalanceResponse) SetBalances(v []RosettaAmount) {
	o.Balances = v
}

// GetCoins returns the Coins field value if set, zero value otherwise.
func (o *RosettaAccountBalanceResponse) GetCoins() []RosettaCoin {
	if o == nil || o.Coins == nil {
		var ret []RosettaCoin
		return ret
	}
	return o.Coins
}

// GetCoinsOk returns a tuple with the Coins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RosettaAccountBalanceResponse) GetCoinsOk() ([]RosettaCoin, bool) {
	if o == nil || o.Coins == nil {
		return nil, false
	}
	return o.Coins, true
}

// HasCoins returns a boolean if a field has been set.
func (o *RosettaAccountBalanceResponse) HasCoins() bool {
	if o != nil && o.Coins != nil {
		return true
	}

	return false
}

// SetCoins gets a reference to the given []RosettaCoin and assigns it to the Coins field.
func (o *RosettaAccountBalanceResponse) SetCoins(v []RosettaCoin) {
	o.Coins = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *RosettaAccountBalanceResponse) GetMetadata() RosettaAccountBalanceResponseMetadata {
	if o == nil || o.Metadata == nil {
		var ret RosettaAccountBalanceResponseMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RosettaAccountBalanceResponse) GetMetadataOk() (*RosettaAccountBalanceResponseMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RosettaAccountBalanceResponse) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given RosettaAccountBalanceResponseMetadata and assigns it to the Metadata field.
func (o *RosettaAccountBalanceResponse) SetMetadata(v RosettaAccountBalanceResponseMetadata) {
	o.Metadata = &v
}

func (o RosettaAccountBalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["block_identifier"] = o.BlockIdentifier
	}
	if true {
		toSerialize["balances"] = o.Balances
	}
	if o.Coins != nil {
		toSerialize["coins"] = o.Coins
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaAccountBalanceResponse struct {
	value *RosettaAccountBalanceResponse
	isSet bool
}

func (v NullableRosettaAccountBalanceResponse) Get() *RosettaAccountBalanceResponse {
	return v.value
}

func (v *NullableRosettaAccountBalanceResponse) Set(val *RosettaAccountBalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaAccountBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaAccountBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaAccountBalanceResponse(val *RosettaAccountBalanceResponse) *NullableRosettaAccountBalanceResponse {
	return &NullableRosettaAccountBalanceResponse{value: val, isSet: true}
}

func (v NullableRosettaAccountBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaAccountBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


