/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaRelatedOperation Restrict referenced related_operations to identifier indexes < the current operation_identifier.index. This ensures there exists a clear DAG-structure of relations. Since operations are one-sided, one could imagine relating operations in a single transfer or linking operations in a call tree.
type RosettaRelatedOperation struct {
	// Describes the index of related operation.
	Index int32 `json:"index"`
	// Some blockchains specify an operation index that is essential for client use. network_index should not be populated if there is no notion of an operation index in a blockchain (typically most account-based blockchains).
	NetworkIndex *int32 `json:"network_index,omitempty"`
}

// NewRosettaRelatedOperation instantiates a new RosettaRelatedOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaRelatedOperation(index int32) *RosettaRelatedOperation {
	this := RosettaRelatedOperation{}
	this.Index = index
	return &this
}

// NewRosettaRelatedOperationWithDefaults instantiates a new RosettaRelatedOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaRelatedOperationWithDefaults() *RosettaRelatedOperation {
	this := RosettaRelatedOperation{}
	return &this
}

// GetIndex returns the Index field value
func (o *RosettaRelatedOperation) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *RosettaRelatedOperation) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *RosettaRelatedOperation) SetIndex(v int32) {
	o.Index = v
}

// GetNetworkIndex returns the NetworkIndex field value if set, zero value otherwise.
func (o *RosettaRelatedOperation) GetNetworkIndex() int32 {
	if o == nil || o.NetworkIndex == nil {
		var ret int32
		return ret
	}
	return *o.NetworkIndex
}

// GetNetworkIndexOk returns a tuple with the NetworkIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RosettaRelatedOperation) GetNetworkIndexOk() (*int32, bool) {
	if o == nil || o.NetworkIndex == nil {
		return nil, false
	}
	return o.NetworkIndex, true
}

// HasNetworkIndex returns a boolean if a field has been set.
func (o *RosettaRelatedOperation) HasNetworkIndex() bool {
	if o != nil && o.NetworkIndex != nil {
		return true
	}

	return false
}

// SetNetworkIndex gets a reference to the given int32 and assigns it to the NetworkIndex field.
func (o *RosettaRelatedOperation) SetNetworkIndex(v int32) {
	o.NetworkIndex = &v
}

func (o RosettaRelatedOperation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["index"] = o.Index
	}
	if o.NetworkIndex != nil {
		toSerialize["network_index"] = o.NetworkIndex
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaRelatedOperation struct {
	value *RosettaRelatedOperation
	isSet bool
}

func (v NullableRosettaRelatedOperation) Get() *RosettaRelatedOperation {
	return v.value
}

func (v *NullableRosettaRelatedOperation) Set(val *RosettaRelatedOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaRelatedOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaRelatedOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaRelatedOperation(val *RosettaRelatedOperation) *NullableRosettaRelatedOperation {
	return &NullableRosettaRelatedOperation{value: val, isSet: true}
}

func (v NullableRosettaRelatedOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaRelatedOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


