/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RosettaBlockIdentifier The block_identifier uniquely identifies a block in a particular network.
type RosettaBlockIdentifier struct {
	// This is also known as the block hash.
	Hash string `json:"hash"`
	// This is also known as the block height.
	Index int32 `json:"index"`
}

// NewRosettaBlockIdentifier instantiates a new RosettaBlockIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRosettaBlockIdentifier(hash string, index int32) *RosettaBlockIdentifier {
	this := RosettaBlockIdentifier{}
	this.Hash = hash
	this.Index = index
	return &this
}

// NewRosettaBlockIdentifierWithDefaults instantiates a new RosettaBlockIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRosettaBlockIdentifierWithDefaults() *RosettaBlockIdentifier {
	this := RosettaBlockIdentifier{}
	return &this
}

// GetHash returns the Hash field value
func (o *RosettaBlockIdentifier) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *RosettaBlockIdentifier) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *RosettaBlockIdentifier) SetHash(v string) {
	o.Hash = v
}

// GetIndex returns the Index field value
func (o *RosettaBlockIdentifier) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *RosettaBlockIdentifier) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *RosettaBlockIdentifier) SetIndex(v int32) {
	o.Index = v
}

func (o RosettaBlockIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hash"] = o.Hash
	}
	if true {
		toSerialize["index"] = o.Index
	}
	return json.Marshal(toSerialize)
}

type NullableRosettaBlockIdentifier struct {
	value *RosettaBlockIdentifier
	isSet bool
}

func (v NullableRosettaBlockIdentifier) Get() *RosettaBlockIdentifier {
	return v.value
}

func (v *NullableRosettaBlockIdentifier) Set(val *RosettaBlockIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableRosettaBlockIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableRosettaBlockIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRosettaBlockIdentifier(val *RosettaBlockIdentifier) *NullableRosettaBlockIdentifier {
	return &NullableRosettaBlockIdentifier{value: val, isSet: true}
}

func (v NullableRosettaBlockIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRosettaBlockIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


