/*
Stacks Blockchain API

Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

API version: v4.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionEventAsset struct for TransactionEventAsset
type TransactionEventAsset struct {
	AssetEventType *string `json:"asset_event_type,omitempty"`
	AssetId *string `json:"asset_id,omitempty"`
	Sender *string `json:"sender,omitempty"`
	Recipient *string `json:"recipient,omitempty"`
	Amount *string `json:"amount,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewTransactionEventAsset instantiates a new TransactionEventAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionEventAsset() *TransactionEventAsset {
	this := TransactionEventAsset{}
	return &this
}

// NewTransactionEventAssetWithDefaults instantiates a new TransactionEventAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionEventAssetWithDefaults() *TransactionEventAsset {
	this := TransactionEventAsset{}
	return &this
}

// GetAssetEventType returns the AssetEventType field value if set, zero value otherwise.
func (o *TransactionEventAsset) GetAssetEventType() string {
	if o == nil || o.AssetEventType == nil {
		var ret string
		return ret
	}
	return *o.AssetEventType
}

// GetAssetEventTypeOk returns a tuple with the AssetEventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionEventAsset) GetAssetEventTypeOk() (*string, bool) {
	if o == nil || o.AssetEventType == nil {
		return nil, false
	}
	return o.AssetEventType, true
}

// HasAssetEventType returns a boolean if a field has been set.
func (o *TransactionEventAsset) HasAssetEventType() bool {
	if o != nil && o.AssetEventType != nil {
		return true
	}

	return false
}

// SetAssetEventType gets a reference to the given string and assigns it to the AssetEventType field.
func (o *TransactionEventAsset) SetAssetEventType(v string) {
	o.AssetEventType = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *TransactionEventAsset) GetAssetId() string {
	if o == nil || o.AssetId == nil {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionEventAsset) GetAssetIdOk() (*string, bool) {
	if o == nil || o.AssetId == nil {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *TransactionEventAsset) HasAssetId() bool {
	if o != nil && o.AssetId != nil {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *TransactionEventAsset) SetAssetId(v string) {
	o.AssetId = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *TransactionEventAsset) GetSender() string {
	if o == nil || o.Sender == nil {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionEventAsset) GetSenderOk() (*string, bool) {
	if o == nil || o.Sender == nil {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *TransactionEventAsset) HasSender() bool {
	if o != nil && o.Sender != nil {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *TransactionEventAsset) SetSender(v string) {
	o.Sender = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *TransactionEventAsset) GetRecipient() string {
	if o == nil || o.Recipient == nil {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionEventAsset) GetRecipientOk() (*string, bool) {
	if o == nil || o.Recipient == nil {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *TransactionEventAsset) HasRecipient() bool {
	if o != nil && o.Recipient != nil {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *TransactionEventAsset) SetRecipient(v string) {
	o.Recipient = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *TransactionEventAsset) GetAmount() string {
	if o == nil || o.Amount == nil {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionEventAsset) GetAmountOk() (*string, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *TransactionEventAsset) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *TransactionEventAsset) SetAmount(v string) {
	o.Amount = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *TransactionEventAsset) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionEventAsset) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *TransactionEventAsset) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *TransactionEventAsset) SetValue(v string) {
	o.Value = &v
}

func (o TransactionEventAsset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AssetEventType != nil {
		toSerialize["asset_event_type"] = o.AssetEventType
	}
	if o.AssetId != nil {
		toSerialize["asset_id"] = o.AssetId
	}
	if o.Sender != nil {
		toSerialize["sender"] = o.Sender
	}
	if o.Recipient != nil {
		toSerialize["recipient"] = o.Recipient
	}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionEventAsset struct {
	value *TransactionEventAsset
	isSet bool
}

func (v NullableTransactionEventAsset) Get() *TransactionEventAsset {
	return v.value
}

func (v *NullableTransactionEventAsset) Set(val *TransactionEventAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionEventAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionEventAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionEventAsset(val *TransactionEventAsset) *NullableTransactionEventAsset {
	return &NullableTransactionEventAsset{value: val, isSet: true}
}

func (v NullableTransactionEventAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionEventAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


